Tweak rebuild configure

diff --git a/bacula/configure b/bacula/configure
--- a/bacula/configure
+++ b/bacula/configure
@@ -27273,6 +27273,76 @@ fi
 if test "$support_crypto" = "no"; then
    OPENSSL_LIBS=""
    OPENSSL_INC=""
+else
+   { echo "$as_me:$LINENO: checking for EVP_PKEY_encrypt_old in -lssl" >&5
+echo $ECHO_N "checking for EVP_PKEY_encrypt_old in -lssl... $ECHO_C" >&6; }
+if test "${ac_cv_lib_ssl_EVP_PKEY_encrypt_old+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lssl  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char EVP_PKEY_encrypt_old ();
+int
+main ()
+{
+return EVP_PKEY_encrypt_old ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_ssl_EVP_PKEY_encrypt_old=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_ssl_EVP_PKEY_encrypt_old=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_ssl_EVP_PKEY_encrypt_old" >&5
+echo "${ECHO_T}$ac_cv_lib_ssl_EVP_PKEY_encrypt_old" >&6; }
+if test $ac_cv_lib_ssl_EVP_PKEY_encrypt_old = yes; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_OPENSSLv1 1
+_ACEOF
+
+fi
+
 fi
 
 { echo "$as_me:$LINENO: result: $support_tls" >&5
@@ -47311,4 +47381,3 @@ then
 	echo " upgrade it in order to avoid problems with Batch insert mode"
 	echo
 fi
-
