Merge the Bacula Encryption branch to HEAD. Approved by: Kern
git-svn-id: https://bacula.svn.sourceforge.net/svnroot/bacula/trunk@2638 91ce42f0-d328-0410-95d8-f526ca767f89

diff --git a/bacula/configure b/bacula/configure
--- a/bacula/configure
+++ b/bacula/configure
@@ -12770,6 +12770,7 @@ support_conio=yes
 support_gnome=no
 support_wx_console=no
 support_tls=no
+support_crypto=no
 gnome_version=
 wx_version=
 support_static_tools=no
@@ -15880,12 +15881,63 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-   support_tls="yes"
+
+			support_tls="yes"
+			support_crypto="yes"
+
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
  support_tls="no"
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+
+	cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+ #include <openssl/evp.h>
+int
+main ()
+{
+ EVP_sha512();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+   ac_cv_openssl_sha2="yes"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ ac_cv_openssl_sha2="no"
 
 fi
 rm -f conftest.err conftest.$ac_objext \
@@ -15905,9 +15957,23 @@ cat >>confdefs.h <<\_ACEOF
 #define HAVE_TLS 1
 _ACEOF
 
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_CRYPTO 1
+_ACEOF
+
+	fi
+
+	if test "$ac_cv_openssl_sha2" = "yes"; then
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_SHA2 1
+_ACEOF
+
 	fi
 else
 	support_tls="no"
+	support_crypto="no"
 	OPENSSL_LIBS=""
 	OPENSSL_INC=""
 fi
@@ -31536,6 +31602,7 @@ Configuration on `date`:
   readline support:	      ${got_readline} ${PRTREADLINE_SRC}
   TCP Wrappers support:       ${TCPW_MSG} ${WRAPLIBS}
   TLS support:		      ${support_tls}
+  Encryption support:	      ${support_crypto}
   ZLIB support: 	      ${have_zlib}
   enable-smartalloc:	      ${support_smartalloc}
   enable-gnome: 	      ${support_gnome} ${gnome_version}
