- Make default mandir /usr/share/man - Install Bacula man page. - Implement passing of FileSet Enable VSS to FD. - Move main body of reserve drive code into subroutine   so that it can be called multiple times.
git-svn-id: https://bacula.svn.sourceforge.net/svnroot/bacula/trunk@2122 91ce42f0-d328-0410-95d8-f526ca767f89

diff --git a/bacula/configure b/bacula/configure
--- a/bacula/configure
+++ b/bacula/configure
@@ -3204,12 +3204,56 @@ echo "${ECHO_T}$ac_cv_prog_gcc_traditional" >&6
   fi
 fi
 
-if test "x$CC" = xgcc
-then
+if test "x$CC" = xgcc; then
    cat >>confdefs.h <<\_ACEOF
 #define HAVE_GCC 1
 _ACEOF
 
+fi
+# Extract the first word of "$CXX", so it can be a program name with args.
+set dummy $CXX; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_CXX+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $CXX in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_CXX="$CXX" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_CXX="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_path_CXX" && ac_cv_path_CXX="$CXX"
+  ;;
+esac
+fi
+CXX=$ac_cv_path_CXX
+
+if test -n "$CXX"; then
+  echo "$as_me:$LINENO: result: $CXX" >&5
+echo "${ECHO_T}$CXX" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+if test ! -e $CXX; then
+   { { echo "$as_me:$LINENO: error: Unable to find C++ compiler" >&5
+echo "$as_me: error: Unable to find C++ compiler" >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 # Find a good install program.  We prefer a C program (faster),
@@ -4716,6 +4760,14 @@ if test x$sbindir = x'${exec_prefix}/sbin' ; then
     sbindir=${exec_prefix}/sbin
 fi
 sbindir=`eval echo ${sbindir}`
+
+# -------------------------------------------------------------------------
+#  If the user has not set --mandir, we default to /usr/share/man
+# -------------------------------------------------------------------------
+if test x$mandir = x'${prefix}/man' ; then
+   mandir=/usr/share/man
+fi
+
 
 # ------------------------------------------------------------------
 # All list of languages for which a translation exist. Each
@@ -23143,6 +23195,7 @@ Configuration on `date`:
   Working directory:	      ${working_dir}
   PID directory:	      ${piddir}
   Subsys directory:	      ${subsysdir}
+  Man directory:	      ${mandir}
   C Compiler:		      ${CC} ${CCVERSION}
   C++ Compiler: 	      ${CXX} ${CXXVERSION}
   Compiler flags:	      ${WCFLAGS} ${CFLAGS}
