Move shared object numbers into version.h + use -release for libtool rather than -version-info

diff --git a/bacula/configure b/bacula/configure
--- a/bacula/configure
+++ b/bacula/configure
@@ -811,6 +811,21 @@ DATE
 LSMDATE
 BACULA
 post_host
+LIBBAC_LT_CURRENT
+LIBBAC_LT_REVISION
+LIBBAC_LT_AGE
+LIBBACCFG_LT_CURRENT
+LIBBACCFG_LT_REVISION
+LIBBACCFG_LT_AGE
+LIBBACPY_LT_CURRENT
+LIBBACPY_LT_REVISION
+LIBBACPY_LT_AGE
+LIBBACSQL_LT_CURRENT
+LIBBACSQL_LT_REVISION
+LIBBACSQL_LT_AGE
+LIBBACFIND_LT_CURRENT
+LIBBACFIND_LT_REVISION
+LIBBACFIND_LT_AGE
 CC
 CFLAGS
 LDFLAGS
@@ -2340,7 +2355,28 @@ BACULA=${BACULA:-Bacula}
 VERSION=`sed -n -e 's/^.*VERSION.*"\(.*\)"$/\1/p' ${srcdir}/src/version.h`
 DATE=`sed -n -e 's/^.* \t*BDATE.*"\(.*\)"$/\1/p' ${srcdir}/src/version.h`
 LSMDATE=`sed -n -e 's/^.*LSMDATE.*"\(.*\)"$/\1/p' ${srcdir}/src/version.h`
+
+LIBBAC_LT_CURRENT=`sed -n -e 's/^.*LIBBAC_LT_CURRENT *\(.*\)$/\1/p' ${srcdir}/src/version.h`
+LIBBAC_LT_REVISION=`sed -n -e 's/^.*LIBBAC_LT_REVISION *\(.*\)$/\1/p' ${srcdir}/src/version.h`
+LIBBAC_LT_AGE=`sed -n -e 's/^.*LIBBAC_LT_AGE *\(.*\)$/\1/p' ${srcdir}/src/version.h`
+LIBBACCFG_LT_CURRENT=`sed -n -e 's/^.*LIBBACCFG_LT_CURRENT *\(.*\)$/\1/p' ${srcdir}/src/version.h`
+LIBBACCFG_LT_REVISION=`sed -n -e 's/^.*LIBBACCFG_LT_REVISION *\(.*\)$/\1/p' ${srcdir}/src/version.h`
+LIBBACCFG_LT_AGE=`sed -n -e 's/^.*LIBBACCFG_LT_AGE *\(.*\)$/\1/p' ${srcdir}/src/version.h`
+LIBBACPY_LT_CURRENT=`sed -n -e 's/^.*LIBBACPY_LT_CURRENT *\(.*\)$/\1/p' ${srcdir}/src/version.h`
+LIBBACPY_LT_REVISION=`sed -n -e 's/^.*LIBBACPY_LT_REVISION *\(.*\)$/\1/p' ${srcdir}/src/version.h`
+LIBBACPY_LT_AGE=`sed -n -e 's/^.*LIBBACPY_LT_AGE *\(.*\)$/\1/p' ${srcdir}/src/version.h`
+
+
+LIBBACSQL_LT_CURRENT=`sed -n -e 's/^.*LIBBACSQL_LT_CURRENT *\(.*\)$/\1/p' ${srcdir}/src/version.h`
+LIBBACSQL_LT_REVISION=`sed -n -e 's/^.*LIBBACSQL_LT_REVISION *\(.*\)$/\1/p' ${srcdir}/src/version.h`
+LIBBACSQL_LT_AGE=`sed -n -e 's/^.*LIBBACSQL_LT_AGE *\(.*\)$/\1/p' ${srcdir}/src/version.h`
+
+LIBBACFIND_LT_CURRENT=`sed -n -e 's/^.*LIBBACFIND_LT_CURRENT *\(.*\)$/\1/p' ${srcdir}/src/version.h`
+LIBBACFIND_LT_REVISION=`sed -n -e 's/^.*LIBBACFIND_LT_REVISION *\(.*\)$/\1/p' ${srcdir}/src/version.h`
+LIBBACFIND_LT_AGE=`sed -n -e 's/^.*LIBBACFIND_LT_AGE *\(.*\)$/\1/p' ${srcdir}/src/version.h`
+
 echo "configuring for ${BACULA} $VERSION ($DATE)"
+
 
 
 ac_ext=c
@@ -5947,13 +5983,13 @@ if test "${lt_cv_nm_interface+set}" = set; then
 else
   lt_cv_nm_interface="BSD nm"
   echo "int some_variable = 0;" > conftest.$ac_ext
-  (eval echo "\"\$as_me:5950: $ac_compile\"" >&5)
+  (eval echo "\"\$as_me:5986: $ac_compile\"" >&5)
   (eval "$ac_compile" 2>conftest.err)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:5953: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
+  (eval echo "\"\$as_me:5989: $NM \\\"conftest.$ac_objext\\\"\"" >&5)
   (eval "$NM \"conftest.$ac_objext\"" 2>conftest.err > conftest.out)
   cat conftest.err >&5
-  (eval echo "\"\$as_me:5956: output\"" >&5)
+  (eval echo "\"\$as_me:5992: output\"" >&5)
   cat conftest.out >&5
   if $GREP 'External.*some_variable' conftest.out > /dev/null; then
     lt_cv_nm_interface="MS dumpbin"
@@ -7174,7 +7210,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 7177 "configure"' > conftest.$ac_ext
+  echo '#line 7213 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -9389,11 +9425,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9392: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9428: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9396: \$? = $ac_status" >&5
+   echo "$as_me:9432: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -9728,11 +9764,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9731: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9767: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:9735: \$? = $ac_status" >&5
+   echo "$as_me:9771: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -9833,11 +9869,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9836: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9872: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:9840: \$? = $ac_status" >&5
+   echo "$as_me:9876: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9888,11 +9924,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:9891: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:9927: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:9895: \$? = $ac_status" >&5
+   echo "$as_me:9931: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12644,7 +12680,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 12647 "configure"
+#line 12683 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12740,7 +12776,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<_LT_EOF
-#line 12743 "configure"
+#line 12779 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -14752,11 +14788,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14755: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14791: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14759: \$? = $ac_status" >&5
+   echo "$as_me:14795: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14851,11 +14887,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14854: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14890: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14858: \$? = $ac_status" >&5
+   echo "$as_me:14894: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14903,11 +14939,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14906: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14942: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14910: \$? = $ac_status" >&5
+   echo "$as_me:14946: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -45219,6 +45255,21 @@ DATE!$DATE$ac_delim
 LSMDATE!$LSMDATE$ac_delim
 BACULA!$BACULA$ac_delim
 post_host!$post_host$ac_delim
+LIBBAC_LT_CURRENT!$LIBBAC_LT_CURRENT$ac_delim
+LIBBAC_LT_REVISION!$LIBBAC_LT_REVISION$ac_delim
+LIBBAC_LT_AGE!$LIBBAC_LT_AGE$ac_delim
+LIBBACCFG_LT_CURRENT!$LIBBACCFG_LT_CURRENT$ac_delim
+LIBBACCFG_LT_REVISION!$LIBBACCFG_LT_REVISION$ac_delim
+LIBBACCFG_LT_AGE!$LIBBACCFG_LT_AGE$ac_delim
+LIBBACPY_LT_CURRENT!$LIBBACPY_LT_CURRENT$ac_delim
+LIBBACPY_LT_REVISION!$LIBBACPY_LT_REVISION$ac_delim
+LIBBACPY_LT_AGE!$LIBBACPY_LT_AGE$ac_delim
+LIBBACSQL_LT_CURRENT!$LIBBACSQL_LT_CURRENT$ac_delim
+LIBBACSQL_LT_REVISION!$LIBBACSQL_LT_REVISION$ac_delim
+LIBBACSQL_LT_AGE!$LIBBACSQL_LT_AGE$ac_delim
+LIBBACFIND_LT_CURRENT!$LIBBACFIND_LT_CURRENT$ac_delim
+LIBBACFIND_LT_REVISION!$LIBBACFIND_LT_REVISION$ac_delim
+LIBBACFIND_LT_AGE!$LIBBACFIND_LT_AGE$ac_delim
 CC!$CC$ac_delim
 CFLAGS!$CFLAGS$ac_delim
 LDFLAGS!$LDFLAGS$ac_delim
@@ -45249,21 +45300,6 @@ DD!$DD$ac_delim
 MKISOFS!$MKISOFS$ac_delim
 PYTHON!$PYTHON$ac_delim
 GROWISOFS!$GROWISOFS$ac_delim
-DVDRWMEDIAINFO!$DVDRWMEDIAINFO$ac_delim
-DVDRWFORMAT!$DVDRWFORMAT$ac_delim
-PKGCONFIG!$PKGCONFIG$ac_delim
-QMAKE!$QMAKE$ac_delim
-GMAKE!$GMAKE$ac_delim
-WXCONFIG!$WXCONFIG$ac_delim
-WXFLAGS!$WXFLAGS$ac_delim
-CDRECORD!$CDRECORD$ac_delim
-PIDOF!$PIDOF$ac_delim
-AWK!$AWK$ac_delim
-ARFLAGS!$ARFLAGS$ac_delim
-MAKE_SHELL!$MAKE_SHELL$ac_delim
-LOCAL_LIBS!$LOCAL_LIBS$ac_delim
-LOCAL_CFLAGS!$LOCAL_CFLAGS$ac_delim
-LOCAL_LDFLAGS!$LOCAL_LDFLAGS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 94; then
@@ -45309,6 +45345,21 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+DVDRWMEDIAINFO!$DVDRWMEDIAINFO$ac_delim
+DVDRWFORMAT!$DVDRWFORMAT$ac_delim
+PKGCONFIG!$PKGCONFIG$ac_delim
+QMAKE!$QMAKE$ac_delim
+GMAKE!$GMAKE$ac_delim
+WXCONFIG!$WXCONFIG$ac_delim
+WXFLAGS!$WXFLAGS$ac_delim
+CDRECORD!$CDRECORD$ac_delim
+PIDOF!$PIDOF$ac_delim
+AWK!$AWK$ac_delim
+ARFLAGS!$ARFLAGS$ac_delim
+MAKE_SHELL!$MAKE_SHELL$ac_delim
+LOCAL_LIBS!$LOCAL_LIBS$ac_delim
+LOCAL_CFLAGS!$LOCAL_CFLAGS$ac_delim
+LOCAL_LDFLAGS!$LOCAL_LDFLAGS$ac_delim
 LOCAL_DEFS!$LOCAL_DEFS$ac_delim
 LIBTOOL!$LIBTOOL$ac_delim
 build!$build$ac_delim
@@ -45391,21 +45442,6 @@ HAVE_ASPRINTF!$HAVE_ASPRINTF$ac_delim
 HAVE_SNPRINTF!$HAVE_SNPRINTF$ac_delim
 HAVE_WPRINTF!$HAVE_WPRINTF$ac_delim
 INTLBISON!$INTLBISON$ac_delim
-BUILD_INCLUDED_LIBINTL!$BUILD_INCLUDED_LIBINTL$ac_delim
-USE_INCLUDED_LIBINTL!$USE_INCLUDED_LIBINTL$ac_delim
-CATOBJEXT!$CATOBJEXT$ac_delim
-DATADIRNAME!$DATADIRNAME$ac_delim
-INSTOBJEXT!$INSTOBJEXT$ac_delim
-GENCAT!$GENCAT$ac_delim
-INTLOBJS!$INTLOBJS$ac_delim
-INTL_LIBTOOL_SUFFIX_PREFIX!$INTL_LIBTOOL_SUFFIX_PREFIX$ac_delim
-BAT_DIR!$BAT_DIR$ac_delim
-QWT_INC!$QWT_INC$ac_delim
-QWT_LDFLAGS!$QWT_LDFLAGS$ac_delim
-QWT_LIB!$QWT_LIB$ac_delim
-QWT!$QWT$ac_delim
-WXCONS_CPPFLAGS!$WXCONS_CPPFLAGS$ac_delim
-WXCONS_LDFLAGS!$WXCONS_LDFLAGS$ac_delim
 _ACEOF
 
   if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
@@ -45447,6 +45483,21 @@ _ACEOF
 ac_delim='%!_!# '
 for ac_last_try in false false false false false :; do
   cat >conf$$subs.sed <<_ACEOF
+BUILD_INCLUDED_LIBINTL!$BUILD_INCLUDED_LIBINTL$ac_delim
+USE_INCLUDED_LIBINTL!$USE_INCLUDED_LIBINTL$ac_delim
+CATOBJEXT!$CATOBJEXT$ac_delim
+DATADIRNAME!$DATADIRNAME$ac_delim
+INSTOBJEXT!$INSTOBJEXT$ac_delim
+GENCAT!$GENCAT$ac_delim
+INTLOBJS!$INTLOBJS$ac_delim
+INTL_LIBTOOL_SUFFIX_PREFIX!$INTL_LIBTOOL_SUFFIX_PREFIX$ac_delim
+BAT_DIR!$BAT_DIR$ac_delim
+QWT_INC!$QWT_INC$ac_delim
+QWT_LDFLAGS!$QWT_LDFLAGS$ac_delim
+QWT_LIB!$QWT_LIB$ac_delim
+QWT!$QWT$ac_delim
+WXCONS_CPPFLAGS!$WXCONS_CPPFLAGS$ac_delim
+WXCONS_LDFLAGS!$WXCONS_LDFLAGS$ac_delim
 WX_DIR!$WX_DIR$ac_delim
 TRAY_MONITOR_CPPFLAGS!$TRAY_MONITOR_CPPFLAGS$ac_delim
 TRAY_MONITOR_LDFLAGS!$TRAY_MONITOR_LDFLAGS$ac_delim
@@ -45529,19 +45580,9 @@ DINCLUDE!$DINCLUDE$ac_delim
 DLIB!$DLIB$ac_delim
 DB_LIBS!$DB_LIBS$ac_delim
 WCFLAGS!$WCFLAGS$ac_delim
-WLDFLAGS!$WLDFLAGS$ac_delim
-WRAPLIBS!$WRAPLIBS$ac_delim
-OBJLIST!$OBJLIST$ac_delim
-TAPEDRIVE!$TAPEDRIVE$ac_delim
-PSCMD!$PSCMD$ac_delim
-WIN32!$WIN32$ac_delim
-MACOSX!$MACOSX$ac_delim
-DISTNAME!$DISTNAME$ac_delim
-DISTVER!$DISTVER$ac_delim
-LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 92; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 97; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
@@ -45560,6 +45601,57 @@ fi
 
 cat >>$CONFIG_STATUS <<_ACEOF
 cat >"\$tmp/subs-3.sed" <<\CEOF$ac_eof
+/@[a-zA-Z_][a-zA-Z_0-9]*@/!b
+_ACEOF
+sed '
+s/[,\\&]/\\&/g; s/@/@|#_!!_#|/g
+s/^/s,@/; s/!/@,|#_!!_#|/
+:n
+t n
+s/'"$ac_delim"'$/,g/; t
+s/$/\\/; p
+N; s/^.*\n//; s/[,\\&]/\\&/g; s/@/@|#_!!_#|/g; b n
+' >>$CONFIG_STATUS <conf$$subs.sed
+rm -f conf$$subs.sed
+cat >>$CONFIG_STATUS <<_ACEOF
+CEOF$ac_eof
+_ACEOF
+
+
+ac_delim='%!_!# '
+for ac_last_try in false false false false false :; do
+  cat >conf$$subs.sed <<_ACEOF
+WLDFLAGS!$WLDFLAGS$ac_delim
+WRAPLIBS!$WRAPLIBS$ac_delim
+OBJLIST!$OBJLIST$ac_delim
+TAPEDRIVE!$TAPEDRIVE$ac_delim
+PSCMD!$PSCMD$ac_delim
+WIN32!$WIN32$ac_delim
+MACOSX!$MACOSX$ac_delim
+DISTNAME!$DISTNAME$ac_delim
+DISTVER!$DISTVER$ac_delim
+LTLIBOBJS!$LTLIBOBJS$ac_delim
+_ACEOF
+
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 10; then
+    break
+  elif $ac_last_try; then
+    { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
+echo "$as_me: error: could not make $CONFIG_STATUS" >&2;}
+   { (exit 1); exit 1; }; }
+  else
+    ac_delim="$ac_delim!$ac_delim _$ac_delim!! "
+  fi
+done
+
+ac_eof=`sed -n '/^CEOF[0-9]*$/s/CEOF/0/p' conf$$subs.sed`
+if test -n "$ac_eof"; then
+  ac_eof=`echo "$ac_eof" | sort -nru | sed 1q`
+  ac_eof=`expr $ac_eof + 1`
+fi
+
+cat >>$CONFIG_STATUS <<_ACEOF
+cat >"\$tmp/subs-4.sed" <<\CEOF$ac_eof
 /@[a-zA-Z_][a-zA-Z_0-9]*@/!b end
 _ACEOF
 sed '
@@ -45822,7 +45914,7 @@ s&@abs_builddir@&$ac_abs_builddir&;t t
 s&@abs_top_builddir@&$ac_abs_top_builddir&;t t
 s&@INSTALL@&$ac_INSTALL&;t t
 $ac_datarootdir_hack
-" $ac_file_inputs | sed -f "$tmp/subs-1.sed" | sed -f "$tmp/subs-2.sed" | sed -f "$tmp/subs-3.sed" >$tmp/out
+" $ac_file_inputs | sed -f "$tmp/subs-1.sed" | sed -f "$tmp/subs-2.sed" | sed -f "$tmp/subs-3.sed" | sed -f "$tmp/subs-4.sed" >$tmp/out
 
 test -z "$ac_datarootdir_hack$ac_datarootdir_seen" &&
   { ac_out=`sed -n '/\${datarootdir}/p' "$tmp/out"`; test -n "$ac_out"; } &&
