Commit updated configure
git-svn-id: https://bacula.svn.sourceforge.net/svnroot/bacula/trunk@7881 91ce42f0-d328-0410-95d8-f526ca767f89

diff --git a/bacula/configure b/bacula/configure
--- a/bacula/configure
+++ b/bacula/configure
@@ -40215,6 +40215,7 @@ _ACEOF
 fi
 
 have_acl=no
+have_extended_acl=no
 if test "${ac_cv_header_sys_acl_h+set}" = set; then
   { echo "$as_me:$LINENO: checking for sys/acl.h" >&5
 echo $ECHO_N "checking for sys/acl.h... $ECHO_C" >&6; }
@@ -40561,6 +40562,75 @@ if test $ac_cv_lib_sec_acltotext = yes; then
 		     have_acl=yes;
 		     FDLIBS="-lsec $FDLIBS"
 
+		     { echo "$as_me:$LINENO: checking for acl_totext in -lsec" >&5
+echo $ECHO_N "checking for acl_totext in -lsec... $ECHO_C" >&6; }
+if test "${ac_cv_lib_sec_acl_totext+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lsec  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char acl_totext ();
+int
+main ()
+{
+return acl_totext ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_sec_acl_totext=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_sec_acl_totext=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_sec_acl_totext" >&5
+echo "${ECHO_T}$ac_cv_lib_sec_acl_totext" >&6; }
+if test $ac_cv_lib_sec_acl_totext = yes; then
+
+			    have_extended_acl=yes
+
+
+fi
+
+
 
 fi
 
@@ -40575,6 +40645,13 @@ fi
 if test $have_acl = yes; then
    cat >>confdefs.h <<\_ACEOF
 #define HAVE_ACL 1
+_ACEOF
+
+fi
+
+if test $have_extended_acl = yes; then
+   cat >>confdefs.h <<\_ACEOF
+#define HAVE_EXTENDED_ACL 1
 _ACEOF
 
 fi
