Restore from multiple simultaneous backups
git-svn-id: https://bacula.svn.sourceforge.net/svnroot/bacula/trunk@122 91ce42f0-d328-0410-95d8-f526ca767f89

diff --git a/bacula/Makefile.in b/bacula/Makefile.in
--- a/bacula/Makefile.in
+++ b/bacula/Makefile.in
@@ -34,7 +34,7 @@ MKDIR = $(srcdir)/autoconf/mkinstalldirs
 all: Makefile
 	@for I in ${subdirs}; \
 	  do (cd $$I; echo "==>Entering directory `pwd`"; \
-	      $(MAKE) $@ || (echo ""; echo ""; echo "	====== Error in `pwd` ======"; \
+	      $(MAKE) $@ || (echo ""; echo ""; echo -e "  \a\a ====== Error in `pwd` ======\a\a"; \
 			    echo ""; echo "";)); \
 	done
 
@@ -45,7 +45,7 @@ depend:
 bacula-fd: Makefile	   
 	@for I in ${FDsubdirs}; \
 	  do (cd $$I; echo "==>Entering directory `pwd`"; \
-	      $(MAKE) all || (echo ""; echo ""; echo "	 ====== Error in `pwd` ======"; \
+	      $(MAKE) all || (echo ""; echo ""; echo -e "  \a\a ====== Error in `pwd` ======\a\a"; \
 			    echo ""; echo "";)); \
 	done
 
