Add DESTDIR to Makefile
git-svn-id: https://bacula.svn.sourceforge.net/svnroot/bacula/trunk@9113 91ce42f0-d328-0410-95d8-f526ca767f89

diff --git a/bacula/Makefile.in b/bacula/Makefile.in
--- a/bacula/Makefile.in
+++ b/bacula/Makefile.in
@@ -45,7 +45,7 @@ LIBTOOL_DEPS = @LIBTOOL_DEPS@
 all: Makefile
 	@for I in ${all_subdirs}; \
 	  do (cd $$I; echo "==>Entering directory `pwd`"; \
-	      $(MAKE) $@ || (echo ""; echo ""; echo "  ====== Error in `pwd` ======"; \
+	      $(MAKE) DESTDIR=$(DESTDIR) $@ || (echo ""; echo ""; echo "  ====== Error in `pwd` ======"; \
 			    echo ""; echo "";)); \
 	done
 
@@ -56,7 +56,7 @@ depend:
 bacula-fd: Makefile	   
 	@for I in ${fd_subdirs}; \
 	  do (cd $$I; echo "==>Entering directory `pwd`"; \
-	      $(MAKE) all || (echo ""; echo ""; echo "	 ====== Error in `pwd` ======; \
+	      $(MAKE) DESTDIR=$(DESTDIR) all || (echo ""; echo ""; echo "   ====== Error in `pwd` ======; \
 			    echo ""; echo "";)); \
 	done
 
