- Remove \a and -e from error echos in most Makefiles. - Add more debug code when there are errors on the tape   to try to find Peter's tape problem.
git-svn-id: https://bacula.svn.sourceforge.net/svnroot/bacula/trunk@1901 91ce42f0-d328-0410-95d8-f526ca767f89

diff --git a/bacula/Makefile.in b/bacula/Makefile.in
--- a/bacula/Makefile.in
+++ b/bacula/Makefile.in
@@ -38,7 +38,7 @@ MKDIR = $(srcdir)/autoconf/mkinstalldirs
 all: Makefile
 	@for I in ${all_subdirs}; \
 	  do (cd $$I; echo "==>Entering directory `pwd`"; \
-	      $(MAKE) $@ || (echo ""; echo ""; echo -e "  \a\a ====== Error in `pwd` ======\a\a"; \
+	      $(MAKE) $@ || (echo ""; echo ""; echo "  ====== Error in `pwd` ======"; \
 			    echo ""; echo "";)); \
 	done
 
@@ -49,7 +49,7 @@ depend:
 bacula-fd: Makefile	   
 	@for I in ${fd_subdirs}; \
 	  do (cd $$I; echo "==>Entering directory `pwd`"; \
-	      $(MAKE) all || (echo ""; echo ""; echo -e "  \a\a ====== Error in `pwd` ======\a\a"; \
+	      $(MAKE) all || (echo ""; echo ""; echo "	 ====== Error in `pwd` ======; \
 			    echo ""; echo "";)); \
 	done
 
