Tweak Makefile.in

diff --git a/bacula/Makefile.in b/bacula/Makefile.in
--- a/bacula/Makefile.in
+++ b/bacula/Makefile.in
@@ -57,8 +57,9 @@ depend:
 bacula-fd: Makefile	   
 	@for I in ${fd_subdirs}; \
 	  do (cd $$I; echo "==>Entering directory `pwd`"; \
-	      $(MAKE) DESTDIR=$(DESTDIR) all || (echo ""; echo ""; echo "   ====== Error in `pwd` ======"; \
-			    echo ""; echo ""; false ) || false) || exit 1; \
+	      $(MAKE) DESTDIR=$(DESTDIR) all || \
+	      (echo ""; echo ""; echo "   ====== Error in `pwd` ======"; \
+	       echo ""; echo ""; false ) || false) || exit 1; \
 	done
 
 #-------------------------------------------------------------------------
@@ -155,21 +156,18 @@ Makefile: Makefile.in
 Makefiles:
 	$(SHELL) config.status
 	(cd scripts; \
-	 chmod 755 startmysql stopmysql bacula startit stopit btraceback; \
-	 chmod 755 mtx-changer bconsole gconsole devel_bacula; \
-	 chmod 755 dvd-handler)
-
+	 chmod 755 startmysql stopmysql bacula startit stopit btraceback \
+	    mtx-changer bconsole gconsole devel_bacula dvd-handler)
 	(cd src/cats; \
-	 chmod 755 create_bacula_database update_bacula_tables make_bacula_tables; \
-	 chmod 755 grant_bacula_privileges drop_bacula_tables drop_bacula_database; \
-	 chmod 755 make_catalog_backup delete_catalog_backup)
-
+	 chmod 755 create_bacula_database update_bacula_tables \
+	   make_bacula_tables grant_bacula_privileges drop_bacula_tables \
+	   drop_bacula_database make_catalog_backup delete_catalog_backup)
 	@for I in @DB_BACKENDS@ ; do \
 	  (cd src/cats; \
-	   chmod 755 create_$${I}_database update_$${I}_tables make_$${I}_tables; \
-	   chmod 755 grant_$${I}_privileges drop_$${I}_tables drop_$${I}_database); \
+	   chmod 755 create_$${I}_database update_$${I}_tables \
+	      make_$${I}_tables grant_$${I}_privileges drop_$${I}_tables \
+	      drop_$${I}_database); \
 	  done
-
 	(cd src/qt-console; \
 	 chmod 755 install_conf_file build-depkgs-qt-console)
 
