Start of Recycle Code
git-svn-id: https://bacula.svn.sourceforge.net/svnroot/bacula/trunk@6 91ce42f0-d328-0410-95d8-f526ca767f89

diff --git a/bacula/Makefile.in b/bacula/Makefile.in
--- a/bacula/Makefile.in
+++ b/bacula/Makefile.in
@@ -32,7 +32,10 @@ MKDIR = $(srcdir)/autoconf/mkinstalldirs
 
 all: Makefile
 	@for I in ${subdirs}; \
-	  do (cd $$I; echo "==>Entering directory `pwd`"; $(MAKE) $@ || exit 1); done
+	  do (cd $$I; echo "==>Entering directory `pwd`"; \
+	      $(MAKE) $@ || (echo ""; echo ""; echo "	====== Error in `pwd` ======"; \
+			    echo ""; echo "";)); \
+	done
 
 depend:
 	@for I in ${subdirs}; \
@@ -40,7 +43,10 @@ depend:
 	
 bacula-fd: Makefile	   
 	@for I in ${FDsubdirs}; \
-	  do (cd $$I; echo "==>Entering directory `pwd`"; $(MAKE) all || exit 1); done
+	  do (cd $$I; echo "==>Entering directory `pwd`"; \
+	      $(MAKE) all || (echo ""; echo ""; echo "	 ====== Error in `pwd` ======"; \
+			    echo ""; echo "";)); \
+	done
 
 #-------------------------------------------------------------------------
 configure: autoconf/configure.in autoconf/aclocal.m4 autoconf/acconfig.h autoconf/config.h.in
