Update
git-svn-id: https://bacula.svn.sourceforge.net/svnroot/bacula/trunk@6561 91ce42f0-d328-0410-95d8-f526ca767f89

diff --git a/regress/experimental-all b/regress/experimental-all
--- a/regress/experimental-all
+++ b/regress/experimental-all
@@ -8,4 +8,8 @@ REGRESS_DEBUG=1
 export REGRESS_DEBUG
 scripts/config_dart
 nice ctest -D Experimental -R "all-non-root.*"
+if [ $? != 0 ] ; then
+   echo "ctest failed re-running Submit"
+   ctest -D NightlySubmit
+fi
 REGRESS_DEBUG=${save_debug}
