Upgrades
git-svn-id: https://bacula.svn.sourceforge.net/svnroot/bacula/trunk@6873 91ce42f0-d328-0410-95d8-f526ca767f89

diff --git a/regress/nightly-disk b/regress/nightly-disk
--- a/regress/nightly-disk
+++ b/regress/nightly-disk
@@ -12,5 +12,11 @@ nice ctest -D Nightly -R "^disk:"
 if [ $? != 0 ] ; then
    echo "ctest failed re-running Submit"
    ctest -D NightlySubmit
+   if [ $? != 0 ] ; then
+      echo "Submit failed, waiting 5 mins"
+      sleep 300
+      echo "ctest failed re-running Submit a second time"
+      ctest -D NightlySubmit
+   fi
 fi
 REGRESS_DEBUG=${save_debug}
