Increase retry count
git-svn-id: https://bacula.svn.sourceforge.net/svnroot/bacula/trunk@7048 91ce42f0-d328-0410-95d8-f526ca767f89

diff --git a/regress/nightly-disk-and-tape b/regress/nightly-disk-and-tape
--- a/regress/nightly-disk-and-tape
+++ b/regress/nightly-disk-and-tape
@@ -10,15 +10,18 @@ export REGRESS_DEBUG
 svn update
 scripts/config_dart
 nice ctest -D Experimental -R "^(disk|tape):"
-if [ $? != 0 ] ; then
-   echo "ctest failed re-running Submit"
-   ctest -D ExperimentalSubmit
-   if [ $? != 0 ] ; then
-      echo "Submit failed, waiting 5 mins"
-      sleep 300
-      echo "ctest failed re-running Submit a second time"
-      ctest -D NightlySubmit
+rtn=$?
+i=0
+while [ $i -le 5 ]; do
+   if [ $rtn = 0 ] ; then
+      break;
    fi
-fi
+   echo "Submit failed, waiting 5 mins"
+   sleep 300
+   echo "ctest failed re-running Submit"
+   ctest -D NightlySubmit
+   rtn=$?
+   i=`expr $i + 1`
+done
 REGRESS_DEBUG=${save_debug}
 echo "End nightly-disk-and-tape `date`"
