Enhanced error detection of disk-changer and new 2drive-swap-test
git-svn-id: https://bacula.svn.sourceforge.net/svnroot/bacula/trunk@6884 91ce42f0-d328-0410-95d8-f526ca767f89

diff --git a/regress/tests/disk-changer-test b/regress/tests/disk-changer-test
--- a/regress/tests/disk-changer-test
+++ b/regress/tests/disk-changer-test
@@ -1,4 +1,7 @@
 #!/bin/sh
+rm -rf tmp/disk-changer
+mkdir tmp/disk-changer
+touch tmp/disk-changer/conf 
 echo "Unload drive 0"
 bin/disk-changer tmp/disk-changer/conf unload 1 tmp/disk-changer/drive0 0
 echo "rtn=$?"   
@@ -32,5 +35,11 @@ echo "Load Slot 2 into drive 1 -- error"
 bin/disk-changer tmp/disk-changer/conf load 2 tmp/disk-changer/drive1 1
 echo "rtn=$?"   
 echo "Load Slot 2 in drive 0 -- error"
+bin/disk-changer tmp/disk-changer/conf load 2 tmp/disk-changer/drive0 0
+echo "rtn=$?"   
+echo "Unload drive 0"
+bin/disk-changer tmp/disk-changer/conf unload 1 tmp/disk-changer/drive0 0
+echo "rtn=$?"   
+echo "Load Slot 2 in drive 0 -- should fail"
 bin/disk-changer tmp/disk-changer/conf load 2 tmp/disk-changer/drive0 0
 echo "rtn=$?"   
