ebl  tweak tests to show #897
git-svn-id: https://bacula.svn.sourceforge.net/svnroot/bacula/trunk@5225 91ce42f0-d328-0410-95d8-f526ca767f89

diff --git a/regress/tests/runscript-test b/regress/tests/runscript-test
--- a/regress/tests/runscript-test
+++ b/regress/tests/runscript-test
@@ -94,9 +94,11 @@ grep 'fd: ClientBeforeJob: run command "/bin/false RUN_FD_FAILED2"' tmp/RUN_FD_F
 b=$?
 grep 'dir: AfterJob: run command "/bin/echo RunAfterFailedJob"' tmp/RUN_FD_FAILED.log >/dev/null 2>&1
 c=$?
-grep '*** Backup Error ***' tmp/RUN_FD_FAILED.log >/dev/null 2>&1
+grep 'touching' tmp/RUN_FD_FAILED.log >/dev/null 2>&1
 d=$?
-if [ $a = 0 -a $b = 0 -a $c = 0 -a $d = 0 ]
+grep '*** Backup Error ***' tmp/RUN_FD_FAILED.log >/dev/null 2>&1
+e=$?
+if [ $a = 0 -a $b = 0 -a $c = 0 -a $d = 0 -a $e = 0 ]
 then
    [ "$debug" = 1 ] && echo RUN_FD_FAILED ok
 else
