Tweak get release version from main bacula directory

diff --git a/bacula/release/makeall b/bacula/release/makeall
--- a/bacula/release/makeall
+++ b/bacula/release/makeall
@@ -24,11 +24,32 @@ fi
 
 branch=$1
 
+cwd=`pwd`
+
+# We pull the version $ver from the main bacula source directory
+cd $bacula
+current=`git branch | awk '/*/ { print $2 }'`
+cd bacula
+if [ $?  -ne 0 ]; then
+   echo "Directory: $1 does not exist"
+   exit 1
+fi
+git checkout ${branch}
+git pull ${remote} ${branch}
+if [ $? -ne 0 ]; then
+   echo "Checkout of branch ${branch} failed."
+   exit 1
+fi
+ver=`sed -n -e 's/^.*VERSION.*"\(.*\)"$/\1/p' src/version.h`
+git checkout ${current}
+cd $cwd
+
+
 # ./makeclean
-./makebacularel $bacula $remote $branch
-./makedocsrel $bacula $docs $remote $branch
-./makerescuerel $rescue $remote $branch
-./makewinrel $bacula $remote $branch | tee win$$.log
+./makebacularel $bacula $remote $branch $ver
+./makedocsrel $bacula $docs $remote $branch $ver
+./makerescuerel $rescue $remote $branch $ver
+./makewinrel $bacula $remote $branch $ver | tee win$$.log
 
 # strip ./configure strerror from Win log file
 sed -i -e 's%strerror%%' win$$.log
