04Jul05 - Correct seg fault caused by open() calling sequence change. 03Jul05 - Add new rc-chio-changer script by Rudolf Cejka to   examples/autochangers - Apply Rudolf's changes to bacula.in - Expand the space from 8 to 10 characters in editing   file sizes for restore and dir of catalog, otherwise   GB sizes are truncated -- fixes bug report. - Modify wx-console to know about 10 character widths. - Allow decending into top level directory if recurse=no   is set.  Fixes a bug report. - Install pthreadVCE.dll when installing console or wx-console   on Win32 systems. Fixes bug report.
git-svn-id: https://bacula.svn.sourceforge.net/svnroot/bacula/trunk@2172 91ce42f0-d328-0410-95d8-f526ca767f89

diff --git a/bacula/scripts/bacula.in b/bacula/scripts/bacula.in
--- a/bacula/scripts/bacula.in
+++ b/bacula/scripts/bacula.in
@@ -45,155 +45,155 @@ PIDOF=@PIDOF@
 
 # A function to stop a program.
 killproc() {
-    RC=0
-    # Test syntax.
-    if [ $# = 0 ]; then
-	echo "Usage: killproc {program} [signal]"
-	return 1
-    fi
+   RC=0
+   # Test syntax.
+   if [ $# = 0 ]; then
+      echo "Usage: killproc {program} {port} [signal]"
+      return 1
+   fi
 
-    notset=0
-    # check for third arg to be kill level
-    if [ "$3" != "" ] ; then
-	killlevel=$3
-    else
-	notset=1
-	killlevel="-9"
-    fi
+   notset=0
+   # check for third arg to be kill level
+   if [ "$3" != "" ] ; then
+      killlevel=$3
+   else
+      notset=1
+      killlevel="-9"
+   fi
 
-    # Get base program name
-    base=`basename $1`
+   # Get base program name
+   base=`basename $1`
 
-    # Find pid.
-    pid=`pidofproc $base $2`
+   # Find pid.
+   pid=`pidofproc $base $2`
 
-    # Kill it.
-    if [ "$pid" != "" ] ; then
-	if [ "$notset" = "1" ] ; then
-	    if ps -p $pid>/dev/null 2>&1; then
-		# TERM first, then KILL if not dead
-		kill -TERM $pid 2>/dev/null
-		sleep 1
-		if ps -p $pid >/dev/null 2>&1 ; then
-		    sleep 1
-		    if ps -p $pid >/dev/null 2>&1 ; then
-			sleep 3
-			if ps -p $pid >/dev/null 2>&1 ; then
-			    kill -KILL $pid 2>/dev/null
-			fi
-		    fi
-		fi
+   # Kill it.
+   if [ "$pid" != "" ] ; then
+      if [ "$notset" = "1" ] ; then
+	 if ps -p $pid>/dev/null 2>&1; then
+	     # TERM first, then KILL if not dead
+	     kill -TERM $pid 2>/dev/null
+	     sleep 1
+	     if ps -p $pid >/dev/null 2>&1 ; then
+		 sleep 1
+		 if ps -p $pid >/dev/null 2>&1 ; then
+		     sleep 3
+		     if ps -p $pid >/dev/null 2>&1 ; then
+			 kill -KILL $pid 2>/dev/null
+		     fi
+		 fi
 	     fi
-	     ps -p $pid >/dev/null 2>&1
-	     RC=$?
-	     [ $RC -eq 0 ] && failure "$base shutdown" || success "$base shutdown"
-	#    RC=$((! $RC))
-	# use specified level only
-	else
-	    if ps -p $pid >/dev/null 2>&1; then
-		kill $killlevel $pid 2>/dev/null
-		RC=$?
-		[ $RC -eq 0 ] && success "$base $killlevel" || failure "$base $killlevel"
-	    fi
-	fi
-    else
-	failure "$base shutdown"
-    fi
-    # Remove pid file if any.
-    if [ "$notset" = "1" ]; then
-	rm -f ${PIDDIR}/$base.$2.pid
-    fi
-    return $RC
+	  fi
+	  ps -p $pid >/dev/null 2>&1
+	  RC=$?
+	  [ $RC -eq 0 ] && failure "$base shutdown" || success "$base shutdown"
+      #    RC=$((! $RC))
+      # use specified level only
+      else
+	 if ps -p $pid >/dev/null 2>&1; then
+	    kill $killlevel $pid 2>/dev/null
+	    RC=$?
+	    [ $RC -eq 0 ] && success "$base $killlevel" || failure "$base $killlevel"
+	 fi
+      fi
+   else
+      failure "$base shutdown"
+   fi
+   # Remove pid file if any.
+   if [ "$notset" = "1" ]; then
+      rm -f ${PIDDIR}/$base.$2.pid
+   fi
+   return $RC
 }
 
 # A function to find the pid of a program.
 pidofproc() {
-    pid=""
-    # Test syntax.
-    if [ $# = 0 ] ; then
-	echo "Usage: pidofproc {program}"
-	return 1
-    fi
+   pid=""
+   # Test syntax.
+   if [ $# = 0 ] ; then
+      echo "Usage: pidofproc {program}"
+      return 1
+   fi
 
-    # Get base program name
-    base=`basename $1`
+   # Get base program name
+   base=`basename $1`
 
-    # First try PID file
-    if [ -f ${PIDDIR}/$base.$2.pid ] ; then
-	pid=`head -n 1 ${PIDDIR}/$base.$2.pid`
-	if [ "$pid" != "" ] ; then
-	    echo $pid
-	    return 0
-	fi
-    fi
+   # First try PID file
+   if [ -f ${PIDDIR}/$base.$2.pid ] ; then
+      pid=`head -n 1 ${PIDDIR}/$base.$2.pid`
+      if [ "$pid" != "" ] ; then
+	 echo $pid
+	 return 0
+      fi
+   fi
 
-    # Next try "pidof"
+   # Next try "pidof"
    if [ -x ${PIDOF} ] ; then
-       pid=`${PIDOF} $1`
+      pid=`${PIDOF} $1`
    fi
    if [ "$pid" != "" ] ; then
-       echo $pid
-       return 0
+      echo $pid
+      return 0
    fi
 
-    # Finally try to extract it from ps
-    ${PSCMD} | grep $1 | ${AWK} '{ print $1 }' | tr '\n' ' '
-    return 0
+   # Finally try to extract it from ps
+   ${PSCMD} | grep $1 | ${AWK} '{ print $1 }' | tr '\n' ' '
+   return 0
 }
 
 status() {
-    pid=""
-    # Test syntax.
-    if [ $# = 0 ] ; then
-	echo "Usage: status {program}"
-	return 1
-    fi
+   pid=""
+   # Test syntax.
+   if [ $# = 0 ] ; then
+       echo "Usage: status {program} {port}"
+       return 1
+   fi
 
-    # Get base program name
-    base=`basename $1`
+   # Get base program name
+   base=`basename $1`
 
    # First try "pidof"
    if [ -x ${PIDOF} ] ; then
-       pid=`${PIDOF} $1`
+      pid=`${PIDOF} $1`
    fi
    if [ "$pid" != "" ] ; then
-       echo "$base (pid $pid) is running..."
-       return 0
+      echo "$base (pid $pid) is running..."
+      return 0
    else
-       pid=`${PSCMD} | ${AWK} 'BEGIN { prog=ARGV[1]; ARGC=1 } 
-	     { if ((prog == $2) || (("(" prog ")") == $2) ||
-		  (("[" prog "]") == $2) ||
-		  ((prog ":") == $2)) { print $1 ; exit 0 } }' $1`
-       if [ "$pid" != "" ] ; then
-	   echo "$base (pid $pid) is running..."
-	   return 0
-       fi
+      pid=`${PSCMD} | ${AWK} 'BEGIN { prog=ARGV[1]; ARGC=1 } 
+	    { if ((prog == $2) || (("(" prog ")") == $2) ||
+		 (("[" prog "]") == $2) ||
+		 ((prog ":") == $2)) { print $1 ; exit 0 } }' $1`
+      if [ "$pid" != "" ] ; then
+	 echo "$base (pid $pid) is running..."
+	 return 0
+      fi
    fi
 
-    # Next try the PID files
-    if [ -f ${PIDDIR}/$base.$2.pid ] ; then
-	pid=`head -n 1 ${PIDDIR}/$base.$2.pid`
-	if [ "$pid" != "" ] ; then
-	    echo "$base dead but pid file exists"
-	    return 1
-	fi
-    fi
-    # See if the subsys lock exists
-    if [ -f ${SUBSYSDIR}/$base ] ; then
-	echo "$base dead but subsys locked"
-	return 2
-    fi
-    echo "$base is stopped"
-    return 3
+   # Next try the PID files
+   if [ -f ${PIDDIR}/$base.$2.pid ] ; then
+      pid=`head -n 1 ${PIDDIR}/$base.$2.pid`
+      if [ "$pid" != "" ] ; then
+	 echo "$base dead but pid file exists"
+	 return 1
+      fi
+   fi
+   # See if the subsys lock exists
+   if [ -f ${SUBSYSDIR}/$base ] ; then
+      echo "$base dead but subsys locked"
+      return 2
+   fi
+   echo "$base is stopped"
+   return 3
 }
 
 success() {
-  return 0
+   return 0
 }
 
 failure() {
-  rc=$?
-  return $rc
+   rc=$?
+   return $rc
 }
 
 OS=`uname -s`
@@ -204,85 +204,85 @@ if [ -d "/lib/tls" -a $OS = "Linux" -a `uname -r | cut -c1-3` = "2.4" ] ; then
 fi
 
 case "$1" in
-    start)
-       [ -x ${BACSDBIN}/bacula-sd ] && {
-	  echo "Starting the Bacula Storage daemon"
-	  OPTIONS=''
-	  if [ "${SD_USER}" != '' ]; then
-	     OPTIONS="${OPTIONS} -u ${SD_USER}"
-	  fi
+   start)
+      [ -x ${BACSDBIN}/bacula-sd ] && {
+	 echo "Starting the Bacula Storage daemon"
+	 OPTIONS=''
+	 if [ "${SD_USER}" != '' ]; then
+	    OPTIONS="${OPTIONS} -u ${SD_USER}"
+	 fi
 
-	  if [ "${SD_GROUP}" != '' ]; then
-	     OPTIONS="${OPTIONS} -g ${SD_GROUP}"
-	  fi
+	 if [ "${SD_GROUP}" != '' ]; then
+	    OPTIONS="${OPTIONS} -g ${SD_GROUP}"
+	 fi
 
-	  ${BACSDBIN}/bacula-sd $2 ${OPTIONS} -v -c ${BACSDCFG}/bacula-sd.conf
-       }
+	 ${BACSDBIN}/bacula-sd $2 ${OPTIONS} -v -c ${BACSDCFG}/bacula-sd.conf
+      }
 
-       [ -x ${BACFDBIN}/bacula-fd ] && {
-	  echo "Starting the Bacula File daemon"
-	  OPTIONS=''
-	  if [ "${FD_USER}" != '' ]; then
-	     OPTIONS="${OPTIONS} -u ${FD_USER}"
-	  fi
+      [ -x ${BACFDBIN}/bacula-fd ] && {
+	 echo "Starting the Bacula File daemon"
+	 OPTIONS=''
+	 if [ "${FD_USER}" != '' ]; then
+	    OPTIONS="${OPTIONS} -u ${FD_USER}"
+	 fi
 
-	  if [ "${FD_GROUP}" != '' ]; then
-	     OPTIONS="${OPTIONS} -g ${FD_GROUP}"
-	  fi
+	 if [ "${FD_GROUP}" != '' ]; then
+	    OPTIONS="${OPTIONS} -g ${FD_GROUP}"
+	 fi
 
-	  ${BACFDBIN}/bacula-fd $2 ${OPTIONS} -v -c ${BACFDCFG}/bacula-fd.conf
-       }
+	 ${BACFDBIN}/bacula-fd $2 ${OPTIONS} -v -c ${BACFDCFG}/bacula-fd.conf
+      }
 
-       [ -x ${BACDIRBIN}/bacula-dir ] && { 
-	   sleep 2
-	   echo "Starting the Bacula Director daemon"
-	  OPTIONS=''
-	  if [ "${DIR_USER}" != '' ]; then
-	     OPTIONS="${OPTIONS} -u ${DIR_USER}"
-	  fi
+      [ -x ${BACDIRBIN}/bacula-dir ] && { 
+	  sleep 2
+	  echo "Starting the Bacula Director daemon"
+	 OPTIONS=''
+	 if [ "${DIR_USER}" != '' ]; then
+	    OPTIONS="${OPTIONS} -u ${DIR_USER}"
+	 fi
 
-	  if [ "${DIR_GROUP}" != '' ]; then
-	     OPTIONS="${OPTIONS} -g ${DIR_GROUP}"
-	  fi
+	 if [ "${DIR_GROUP}" != '' ]; then
+	    OPTIONS="${OPTIONS} -g ${DIR_GROUP}"
+	 fi
 
-	  ${BACDIRBIN}/bacula-dir $2 ${OPTIONS} -v -c ${BACDIRCFG}/bacula-dir.conf
-       }
-       ;;
+	 ${BACDIRBIN}/bacula-dir $2 ${OPTIONS} -v -c ${BACDIRCFG}/bacula-dir.conf
+      }
+      ;;
 
-    stop)
-       # Stop the FD first so that SD will fail jobs and update catalog
-       [ -x ${BACFDBIN}/bacula-fd ] && {
-	  echo "Stopping the Bacula File daemon"
-	  killproc ${BACFDBIN}/bacula-fd ${FD_PORT}
-       }
+   stop)
+      # Stop the FD first so that SD will fail jobs and update catalog
+      [ -x ${BACFDBIN}/bacula-fd ] && {
+	 echo "Stopping the Bacula File daemon"
+	 killproc ${BACFDBIN}/bacula-fd ${FD_PORT}
+      }
 
-       [ -x ${BACSDBIN}/bacula-sd ] && {
-	  echo "Stopping the Bacula Storage daemon"
-	  killproc ${BACSDBIN}/bacula-sd ${SD_PORT}
-       }
+      [ -x ${BACSDBIN}/bacula-sd ] && {
+	 echo "Stopping the Bacula Storage daemon"
+	 killproc ${BACSDBIN}/bacula-sd ${SD_PORT}
+      }
 
-       [ -x ${BACDIRBIN}/bacula-dir ] && {
-	  echo "Stopping the Bacula Director daemon"
-	  killproc ${BACDIRBIN}/bacula-dir ${DIR_PORT}
-       }
-       echo
-       ;;
+      [ -x ${BACDIRBIN}/bacula-dir ] && {
+	 echo "Stopping the Bacula Director daemon"
+	 killproc ${BACDIRBIN}/bacula-dir ${DIR_PORT}
+      }
+      echo
+      ;;
 
-    restart)
-       $0 stop
-       sleep 5
-       $0 start
-       ;;
+   restart)
+      $0 stop
+      sleep 5
+      $0 start
+      ;;
 
-    status)
-       [ -x ${BACSDBIN}/bacula-sd   ] && status ${BACSDBIN}/bacula-sd  ${SD_PORT}
-       [ -x ${BACFDBIN}/bacula-fd   ] && status ${BACFDBIN}/bacula-fd  ${FD_PORT}
-       [ -x ${BACDIRBIN}/bacula-dir ] && status ${BACDIRBIN}/bacula-dir ${DIR_PORT}
-       ;;
+   status)
+      [ -x ${BACSDBIN}/bacula-sd   ] && status ${BACSDBIN}/bacula-sd  ${SD_PORT}
+      [ -x ${BACFDBIN}/bacula-fd   ] && status ${BACFDBIN}/bacula-fd  ${FD_PORT}
+      [ -x ${BACDIRBIN}/bacula-dir ] && status ${BACDIRBIN}/bacula-dir ${DIR_PORT}
+      ;;
 
-    *)
-       echo "Usage: $0 {start|stop|restart|status}"
-       exit 1
-       ;;
+   *)
+      echo "Usage: $0 {start|stop|restart|status}"
+      exit 1
+      ;;
 esac
 exit 0
