kes  Make bscan ignore ACL streams. kes  Update projects files with new Feature Requests. kes  Generate current English and French manuals and upload      them to the site. kes  Update the home page to include the new British/French flags to      switch between translations. Work done by Alexandre Baron. kes  Make disk-changer script print an error message if the changer      directory is not defined. kes  Create a generic DB routine for getting an int (32/64 bit) from      the DB. kes  Add more migration code. kes  Add a few more files to .cvsignore here and there.
git-svn-id: https://bacula.svn.sourceforge.net/svnroot/bacula/trunk@3201 91ce42f0-d328-0410-95d8-f526ca767f89

diff --git a/bacula/scripts/disk-changer.in b/bacula/scripts/disk-changer.in
--- a/bacula/scripts/disk-changer.in
+++ b/bacula/scripts/disk-changer.in
@@ -108,6 +108,11 @@ check_parm_count() {
 get_dir() {
    bn=`basename $device`
    dir=`echo "$device" | sed -e s%/$bn%%g -`
+   if [ ! -d $dir ]; then
+      echo "ERROR: Autochanger directory \"$dir\" does not exist.\n"
+      echo "	   You must create it.\n"
+      exit 1
+   fi
 }
 
 
