Update doc
git-svn-id: https://bacula.svn.sourceforge.net/svnroot/bacula/trunk@447 91ce42f0-d328-0410-95d8-f526ca767f89

diff --git a/bacula/autoconf/configure.in b/bacula/autoconf/configure.in
--- a/bacula/autoconf/configure.in
+++ b/bacula/autoconf/configure.in
@@ -1345,7 +1345,6 @@ esac
 
 AC_SUBST(hostname)
 
-
 LIBS="$PTHREAD_LIB $LIBS"
 
 AC_DEFINE_UNQUOTED(lld, "$lld")
@@ -1359,6 +1358,20 @@ AC_SUBST(DISTVER)
 dnl# common parts of the Makefile
 MCOMMON=./autoconf/Make.common
 AC_SUBST_FILE(MCOMMON)
+
+dnl# Insanity check
+if test "x${subsysdir}" = "x${sbindir}" ; then
+   echo " "
+   echo " "
+   echo "You have set both --sbindir and --with-subsys-dir"
+   echo "  equal to: ${subsysdir} "
+   echo "This is not permitted. Please reconfigure."
+   echo " "
+   echo "Aborting configuration ..."
+   echo " "
+   echo " "
+   exit 1
+fi 
 
 AC_OUTPUT([autoconf/Make.common \
 	   Makefile \
@@ -1444,6 +1457,18 @@ fi
 CCVERSION=`${CC} --version | cut -b-15`
 CXXVERSION=`${CXX} --version | cut -b-15`
 
+if test "x${subsysdir}" = "x${sbindir}" ; then
+   echo " "
+   echo " "
+   echo "You have set --sbindir and --with-subsys-dir"
+   echo "  both equal to: ${subsysdir} "
+   echo "  This is not permitted. Please reconfigure."
+   echo "Aborting configuration ..."
+   echo " "
+   echo " "
+   exit 1
+fi 
+
 echo "
 Configuration on `date`:
 
@@ -1452,8 +1477,10 @@ Configuration on `date`:
   Source code location:       ${srcdir}
   Install binaries:	      ${sbindir}
   Install config files:       ${sysconfdir}
-  Scripts directory	      ${scriptdir}
-  Working directory	      ${working_dir}
+  Scripts directory:	      ${scriptdir}
+  Working directory:	      ${working_dir}
+  PID directory:	      ${piddir}
+  Subsys directory:	      ${subsysdir}
   C Compiler:		      ${CC} ${CCVERSION}
   C++ Compiler: 	      ${CXX} ${CXXVERSION}
   Compiler flags:	      ${WCFLAGS} ${CFLAGS} 
diff --git a/bacula/configure b/bacula/configure
--- a/bacula/configure
+++ b/bacula/configure
@@ -9536,7 +9536,6 @@ esac
 
 
 
-
 LIBS="$PTHREAD_LIB $LIBS"
 
 cat >> confdefs.h <<EOF
@@ -9555,6 +9554,19 @@ EOF
 
 MCOMMON=./autoconf/Make.common
 
+
+if test "x${subsysdir}" = "x${sbindir}" ; then
+   echo " "
+   echo " "
+   echo "You have set both --sbindir and --with-subsys-dir"
+   echo "  equal to: ${subsysdir} "
+   echo "This is not permitted. Please reconfigure."
+   echo " "
+   echo "Aborting configuration ..."
+   echo " "
+   echo " "
+   exit 1
+fi 
 
 trap '' 1 2 15
 cat > confcache <<\EOF
@@ -10186,6 +10198,18 @@ fi
 CCVERSION=`${CC} --version | cut -b-15`
 CXXVERSION=`${CXX} --version | cut -b-15`
 
+if test "x${subsysdir}" = "x${sbindir}" ; then
+   echo " "
+   echo " "
+   echo "You have set --sbindir and --with-subsys-dir"
+   echo "  both equal to: ${subsysdir} "
+   echo "  This is not permitted. Please reconfigure."
+   echo "Aborting configuration ..."
+   echo " "
+   echo " "
+   exit 1
+fi 
+
 echo "
 Configuration on `date`:
 
@@ -10194,8 +10218,10 @@ Configuration on `date`:
   Source code location:       ${srcdir}
   Install binaries:	      ${sbindir}
   Install config files:       ${sysconfdir}
-  Scripts directory	      ${scriptdir}
-  Working directory	      ${working_dir}
+  Scripts directory:	      ${scriptdir}
+  Working directory:	      ${working_dir}
+  PID directory:	      ${piddir}
+  Subsys directory:	      ${subsysdir}
   C Compiler:		      ${CC} ${CCVERSION}
   C++ Compiler: 	      ${CXX} ${CXXVERSION}
   Compiler flags:	      ${WCFLAGS} ${CFLAGS} 
