Add --enable-wx-console
git-svn-id: https://bacula.svn.sourceforge.net/svnroot/bacula/trunk@1206 91ce42f0-d328-0410-95d8-f526ca767f89

diff --git a/bacula/autoconf/configure.in b/bacula/autoconf/configure.in
--- a/bacula/autoconf/configure.in
+++ b/bacula/autoconf/configure.in
@@ -19,7 +19,7 @@ dnl search for true and false programs.
 AC_PATH_PROGS(TRUEPRG, true, :)
 AC_PATH_PROGS(FALSEPRG, false, :)
 
-AC_CANONICAL_HOST
+#AC_CANONICAL_HOST
 
 dnl bacula version
 VERSION=`sed -n -e 's/^.*VERSION.*"\(.*\)"$/\1/p' ${srcdir}/src/version.h`
@@ -63,6 +63,7 @@ AC_PATH_PROG(RANLIB, ranlib, ranlib)
 AC_PATH_PROG(OPENSSL, openssl, none)
 AC_PATH_PROG(MTX, mtx, mtx)
 AC_PATH_PROG(PKGCONFIG, pkg-config, pkg-config)
+AC_PATH_PROG(WXCONFIG, wx-config, wx-config)
 
 test -n "$ARFLAG" || ARFLAGS="cr"
 AC_SUBST(ARFLAGS)
@@ -145,6 +146,7 @@ support_smartalloc=yes
 support_readline=yes
 support_conio=yes
 support_gnome=no
+support_wx_console=no
 gnome_version=
 support_static_tools=no
 support_static_fd=no
@@ -174,10 +176,10 @@ if test x$support_gnome = xyes; then
   abc=`$PKGCONFIG --exists libgnomeui-2.0`
   pkg=$?
   if test $pkg = 0; then
-     GNOME_INCLUDEDIR=`pkg-config --cflags-only-I libgnomeui-2.0`
-     GNOMEUI_LIBS=`pkg-config --libs-only-l libgnomeui-2.0`
-     GNOME_LIBDIR=`pkg-config --libs libgnomeui-2.0`
-     GNOME_LIBS=`pkg-config --libs-only-l libgnomeui-2.0`
+     GNOME_INCLUDEDIR=`$PKGCONFIG --cflags-only-I libgnomeui-2.0`
+     GNOMEUI_LIBS=`$PKGCONFIG --libs-only-l libgnomeui-2.0`
+     GNOME_LIBDIR=`$PKGCONFIG --libs libgnomeui-2.0`
+     GNOME_LIBS=`$PKGCONFIG --libs-only-l libgnomeui-2.0`
      AC_SUBST(GNOME_INCLUDEDIR)
      AC_SUBST(GNOMEUI_LIBS)
      AC_SUBST(GNOME_LIBDIR)
@@ -192,6 +194,36 @@ dnl do 1.4 stuff
   fi
 fi
 AC_SUBST(GNOME_DIR)
+
+
+# -------------------------------------------
+# wx-console (default off)
+# -------------------------------------------
+AC_ARG_ENABLE(wx-console,
+  [  --enable-wx-console      enable build of wxWidgets console [disabled]],
+  [if test x$enableval = xyes; then
+    support_wx_console=yes
+  fi])
+
+WX_DIR=
+if test x$support_wx_console = xyes; then
+  abc=`$WXCONFIG --cppflags`
+  pkg=$?
+  if test $pkg = 0; then
+     WXCONS_CPPFLAGS=`$WXCONFIG --cppflags`
+     WXCONS_LDFLAGS=`$WXCONFIG --libs`
+     AC_SUBST(WXCONS_CPPFLAGS)
+     AC_SUBST(WXCONS_LDFLAGS)
+     WX_DIR=src/wx-console
+  else
+     echo " "
+     echo "wx-config program not found. wx-console disabled."
+     echo " "
+     support_wx_console=no
+  fi
+fi
+AC_SUBST(WX_DIR)
+
 
 
 # -------------------------------------------
@@ -278,12 +310,15 @@ AC_ARG_ENABLE(static-cons,
 
 STATIC_CONS=
 STATIC_GNOME_CONS=
+STATIC_WX_CONS=
 if test x$support_static_cons = xyes; then
    STATIC_CONS="static-bconsole"
    STATIC_GNOME_CONS="static-gnome-console"
+   STATIC_WX_CONS="static-wx-console"
 fi
 AC_SUBST(STATIC_CONS)
 AC_SUBST(STATIC_GNOME_CONS)
+AC_SUBST(STATIC_WX_CONS)
 
 # -------------------------------------------
 # client_only  (default off)
@@ -1566,8 +1601,8 @@ AC_OUTPUT([autoconf/Make.common \
 	   scripts/bacula.desktop.gnome2 \
 	   scripts/bacula.desktop.gnome1.consolehelper \
 	   scripts/bacula.desktop.gnome2.consolehelper \
-	scripts/bacula.desktop.gnome1.xsu \
-	scripts/bacula.desktop.gnome2.xsu \
+	   scripts/bacula.desktop.gnome1.xsu \
+	   scripts/bacula.desktop.gnome2.xsu \
 	   scripts/gnome-console.console_apps \
 	   scripts/mtx-changer \
 	   doc/Makefile \
@@ -1579,6 +1614,7 @@ AC_OUTPUT([autoconf/Make.common \
 	   src/gnome-console/gnome-console.conf \
 	   src/gnome2-console/Makefile \
 	   src/gnome2-console/gnome-console.conf \
+	   src/wx-console/Makefile \
 	   src/tconsole/Makefile \
 	   src/dird/Makefile \
 	   src/dird/bacula-dir.conf \
@@ -1736,6 +1772,7 @@ Configuration on `date`:
   ZLIB support: 	      ${have_zlib}
   enable-smartalloc:	      ${support_smartalloc} 
   enable-gnome: 	      ${support_gnome} ${gnome_version}
+  enable-wx-console:	      ${support_wx_console}
   client-only:		      ${build_client_only}
 
   " > config.out
