Add code to detect glibc complaints
git-svn-id: https://bacula.svn.sourceforge.net/svnroot/bacula/trunk@4889 91ce42f0-d328-0410-95d8-f526ca767f89

diff --git a/regress/scripts/check_for_zombie_jobs b/regress/scripts/check_for_zombie_jobs
--- a/regress/scripts/check_for_zombie_jobs
+++ b/regress/scripts/check_for_zombie_jobs
@@ -49,3 +49,11 @@ if [ $? = 0 ] ; then
   echo " "
 fi
 
+grep "glibc detected" tmp/log*.out 2>&1 >/dev/null
+if [ $? = 0 ] ; then
+  echo " "
+  echo "  !!!! glibc detected Error in log output !!!!"
+  echo "  !!!! glibc detected Error in log output !!!!" >>test.out
+  echo " "
+fi
+
