Update
git-svn-id: https://bacula.svn.sourceforge.net/svnroot/bacula/trunk@5621 91ce42f0-d328-0410-95d8-f526ca767f89

diff --git a/regress/scripts/functions b/regress/scripts/functions
--- a/regress/scripts/functions
+++ b/regress/scripts/functions
@@ -113,6 +113,10 @@ check_two_logs()
    if test $? -eq 0; then
       rstat=2
    fi
+   grep "^  Termination: *Verify Differences" tmp/log2.out 2>&1 >/dev/null
+   if test $? -eq 0; then
+      rstat=3
+   fi
 }
 
 check_restore_diff()
@@ -132,16 +136,18 @@ end_test()
    if [ $dstat != 0 -o $bstat != 0 -o $rstat != 0 ] ; then
       echo " "
       echo " "
-      echo "  !!!!! $TestName failed!!! !!!!! "
-      echo "  !!!!! $TestName failed!!! !!!!! " >>test.out
+      echo "  !!!!! $TestName failed!!! `date +%R:%S` !!!!! "
+      echo "  !!!!! $TestName failed!!! `date +%R:%S` !!!!! " >>test.out
       if [ $bstat != 0 -o $rstat != 0 ] ; then
-         echo "  !!!!! Bad Job termination status     !!!!! "
-         echo "  !!!!! Bad Job termination status     !!!!! " >>test.out
-         echo "        bstat=$bstat rstat=$rstat dstat=$dstat"
+         echo "  !!!!! Bad termination status       !!!!! "
+         echo "  !!!!! Bad termination status       !!!!! " >>test.out
+         echo "   Status: backup=$bstat restore=$rstat diff=$dstat"
+         echo "   Status: backup=$bstat restore=$rstat diff=$dstat" >>test.out
       else
          echo "  !!!!! Restored files differ          !!!!! "
          echo "  !!!!! Restored files differ          !!!!! " >>test.out
-         echo "        bstat=$bstat rstat=$rstat dstat=$dstat"
+         echo "   Status: backup=$bstat restore=$rstat diff=$dstat"
+         echo "   Status: backup=$bstat restore=$rstat diff=$dstat" >>test.out
       fi
       echo " "
    else
